import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Share2, Download, FileText } from 'lucide-react';

const BriefingResult = ({ content, onClose }) => {
    if (!content) return null;

    return (
        <AnimatePresence>
            <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4"
            >
                <motion.div
                    initial={{ scale: 0.9, opacity: 0, y: 20 }}
                    animate={{ scale: 1, opacity: 1, y: 0 }}
                    exit={{ scale: 0.9, opacity: 0, y: 20 }}
                    className="bg-[#0F111A] border border-slate-700 w-full max-w-2xl rounded-2xl shadow-2xl flex flex-col max-h-[85vh] overflow-hidden"
                >
                    {/* Header */}
                    <div className="flex items-center justify-between px-6 py-4 border-b border-slate-700 bg-slate-900/50">
                        <div className="flex items-center gap-3">
                            <div className="p-2 rounded-lg bg-indigo-500/10 text-indigo-400">
                                <FileText size={20} />
                            </div>
                            <div>
                                <h2 className="text-lg font-bold text-slate-100">Daily Executive Briefing</h2>
                                <p className="text-xs text-slate-400">Generated by Synoptic AI Orchestrator</p>
                            </div>
                        </div>
                        <div className="flex items-center gap-2">
                            <button
                                onClick={() => { }}
                                className="p-2 text-slate-400 hover:text-white hover:bg-white/5 rounded-lg transition-colors"
                                title="Share"
                            >
                                <Share2 size={18} />
                            </button>
                            <button
                                onClick={() => { }}
                                className="p-2 text-slate-400 hover:text-white hover:bg-white/5 rounded-lg transition-colors"
                                title="Download PDF"
                            >
                                <Download size={18} />
                            </button>
                            <div className="w-px h-6 bg-slate-700 mx-1" />
                            <button
                                onClick={onClose}
                                className="p-2 text-slate-400 hover:text-rose-400 hover:bg-rose-500/10 rounded-lg transition-colors"
                            >
                                <X size={18} />
                            </button>
                        </div>
                    </div>

                    {/* Content */}
                    <div className="overflow-y-auto p-6 md:p-8 space-y-6 scrollbar-thin scrollbar-thumb-slate-700 scrollbar-track-transparent">
                        {/* We can parse markdown here or just display pre-formatted blocks */}
                        {content.split('\n\n').map((block, i) => (
                            <div key={i} className="text-slate-300 leading-relaxed">
                                {block.startsWith('##') ? (
                                    <h3 className="text-xl font-bold text-white mb-3 mt-4 flex items-center gap-2">
                                        <span className="w-1 h-6 bg-indigo-500 rounded-full inline-block" />
                                        {block.replace('##', '').trim()}
                                    </h3>
                                ) : block.startsWith('•') ? (
                                    <ul className="list-disc list-inside space-y-1 ml-2">
                                        {block.split('\n').map((item, j) => (
                                            <li key={j} className="text-slate-300">{item.replace('•', '').trim()}</li>
                                        ))}
                                    </ul>
                                ) : (
                                    <p>{block}</p>
                                )}
                            </div>
                        ))}
                    </div>

                    {/* Footer */}
                    <div className="px-6 py-4 border-t border-slate-700 bg-slate-900/50 flex justify-between items-center text-xs text-slate-500 font-mono">
                        <span>CONFIDENTIAL - INTERNAL USE ONLY</span>
                        <span>ID: {Math.random().toString(36).substr(2, 9).toUpperCase()}</span>
                    </div>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    );
};

export default BriefingResult;
